### PR TITLE
remove 'the' preposition from comparator inputs

### LINKED ISSUE #1079: Ignore “the “ when sorting
*Case insensitive

## Steps to Reproduce

1. Create a thought
2. Activate `sortContext`
3. Import the following thoughts as children:

- a
- theatre
- d
- the c
- b

## Current Behavior

- a
- b
- d
- the c
- theatre

## Expected Behavior

- a
- b
- the c
- d
- theatre

### PR DESCRIPTION
**Pull request by onurpolattimur**
fixes #1079 

Notes: This doesn't work for home context. There is already opened issue related to this #1080

### CODE REVIEW

File: src/util/compareThought.ts [hunk 1]
```diff
@@ -5,10 +5,23 @@ import { EMOJI_REGEX } from '../constants'
...
 const regexShortDateWithSlash = /\d{1,2}\/\d{1,2}/
+const ignoredPrefixes = ['the ']
 
 /** Remove emojis and trailing/leading spaces from camparator inputs using regex. */
 const removeEmojisAndSpaces = (str: string) => str.replace(EMOJI_REGEX, '').trim()
 
+/** Remove ignored prefixes from comparator inputs. */
+const removeIgnoredPrefixes = (str: string) => {
+  const ignoredKeywords = ignoredPrefixes.join('|')
+  const regex = new RegExp(`^(${ignoredKeywords})(.*)`, 'gm')
```
Comment (raineorshine) [inline src/util/compareThought.ts:16]: You can move the regex to the module scope since it does not change between invocations. Regex instantiation is not trivial like object literals.

**Review by raineorshine — CHANGES_REQUESTED** [review]
Thanks for the contribution! I like your approach.

**Comment by raineorshine** [comment]
Please add a unit test at your convenience.

File: src/util/compareThought.ts (hunk 1 above)
Comment (onurpolattimur) [reply src/util/compareThought.ts]: Yes, you are right. Also I have moved the ignoredPrefixes variable to `constants.ts`. Because one day you may need to access these ignored prefixes.
