### PR TITLE
cursorCleared: remove asyncFocus

### LINKED ISSUE #2705: clearThought does not work after cursorForward
## Steps to Reproduce

```
- a
  - b
```

1. Set the cursor on `a`.
2. Set the caret on `a` so the keyboard opens.
3. Swipe ← to activate cursorForward.
4. Swipe →←→ to activate clearThought.

## Current Behavior

Nothing happens.

## Expected Behavior

clearThought should work as normal.

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #2705 

Calling `asyncFocus()` after `clearThought` triggers the editable's `onBlur` which dispatches `cursorCleared({ value: false })`, which undoes the whole `clearThought` operation.

Screenshot 2025-01-15 at 10 23 33

Without `asyncFocus()`, `clearThought` can proceed as intended.

Screenshot 2025-01-15 at 10 24 26

`asyncFocus()` was triggered on any `clearThought`, and the reason why it's failing in this specific case is because `selection.isText()` return `true` on a basic `clearThought`, and `false` after `cursorForward`. The reason for this is because the native selection sets `focusNode` to the text node within the editable, while `cursorForward` is setting `focusNode` to the editable `div`.

### CODE REVIEW

File: src/components/Editable/useEditMode.ts [hunk 1]
```diff
@@ -51,6 +51,7 @@ const useEditMode = ({
           selection.clear()
         } else {
           selection.set(contentRef.current, { offset: editingCursorOffset || 0 })
+          if (isTouch && isSafari()) contentRef.current?.focus()
```
Comment (ethan-james) [inline src/components/Editable/useEditMode.ts:54]: I guess this is the same fix from #2752 that is already captured in #2753.

In this case, the steps to reproduce that bad focus behavior are:

1. `clearThought` gesture on the active cursor
2. Close the keyboard
3. `clearThought` gesture again
4. Keyboard doesn't open

**Review by raineorshine — APPROVED** [review]
Thanks so much for the clear explanation. It looks like I have been a bit too liberal with `asyncFocus`! It works great when there is no focus, but causes problems if the editable already has the focus, and it definitely doesn't work well with `clearThought`.

**Comment by ethan-james** [comment]
Right on, I tested it when there is no focus and it seemed OK. I know `asyncFocus` is in there to solve a problem, but I couldn't find any case that would break without it here.

I'd still like to figure out why the `selection.isText()` thing is breaking, but like I say, I didn't see any example where leaving `asyncFocus` in would improve things.

**Comment by raineorshine** [comment]
Yep. It's possible we might be able to implement a more general fix, but I've opened #2753 for that.
