### PR TITLE
fixes scaling of toolbars' scroll arrows

### LINKED ISSUE #758: Toolbar: Scroll arrows do not scale with toolbar
When the font size is increased, the scroll arrows should scale with the toolbar. When they are not scaled properly:

1. The scroll arrows are not vertically centered
2. The black background does not cover the toolbar.

Screen Shot 2020-06-24 at 7 49 12 AM

### PR DESCRIPTION
**Pull request by anmolarora1**
fixes #758

### CODE REVIEW

**Comment by raineorshine** [comment]
Screen Shot 2020-06-25 at 8 02 59 AM

The arrows are much larger than they should be at font size 18.

**Comment by raineorshine** [comment]
Also, the arrows are not square, so you can't set the width and height to the same value.

**Comment by anmolarora1** [comment]
> Screen Shot 2020-06-25 at 8 02 59 AM
> 
> The arrows are much larger than they should be at font size 18.



> Screen Shot 2020-06-25 at 8 02 59 AM
> 
> The arrows are much larger than they should be at font size 18.

Updated in the latest commit to match the former dimensions

**Comment by raineorshine** [comment]
@shresthabijay Can you test this? Thanks!

File: src/components/Toolbar.js [hunk 1]
```diff
@@ -247,13 +248,13 @@ const Toolbar = ({ cursorOnTableView, cursorOnAlphabeticalSort, cursorPinOpen, c
                     : id === 'undo' ? fg
                     : id === 'redo' ? fg
                     : 'gray',
-                    width: fontSize,
-                    height: fontSize
+                    width: fontSize + 4,
+                    height: fontSize + 4,
```
Comment (shresthabijay) [inline src/components/Toolbar.js:252]: @anmolarora1 Why are you adding 4 to the `fontSize` ?

**Comment by shresthabijay** [comment]
@raineorshine Arrows are of proper size, vertically aligned and black background covers toolbar in all font sizes. Looks pretty good to me!

File: src/components/Toolbar.js (hunk 1 above)
Comment (raineorshine) [reply src/components/Toolbar.js:252]: The output size of text is slightly different than the output size of the svg icons. We need to add a constant amount to the font size so that they are more evenly matched.
