### PR TITLE
Cursor restored incorrectly after editThought 

### LINKED ISSUE #1389: Undo/Redo: Cursor restored incorrectly after undo archive
## Steps to Reproduce

1. Create thought `a`
2. Set the cursor to `null`
3. Refresh the page
4. Set the cursor to `a`
5. archiveThought
6. undo

## Current Behavior

Cursor disappears. 

## Expected Behavior

Cursor should be on `a`, since that is where the cursor was before `archiveThought` was activated.

Navigation actions immediately _after_ the last edit should be grouped and undone with the edit. 

Navigation actions immediately _before_ the last edit should not be undone.  

(The reverse is true for redo.)

### PR DESCRIPTION
**Pull request by karunkop**
Fixes #1389 , #1618 

## Problem

- Navigation actions right after undoable action were not grouped properly and undone with them

## Solution

- Modified `undoTwice` logic to properly handle mentioned notes in #1618

### CODE REVIEW

File: src/redux-enhancers/undoRedoEnhancer.ts [hunk 1]
```diff
@@ -175,12 +175,9 @@ const undoReducer = (state: State, undoPatches: Patch[]) => {
...
 
-  const undoTwice =
-    penultimateUndoPatch &&
-    !!(
-      (lastAction && NAVIGATION_ACTIONS[lastAction]) ||
-      (penultimateAction && (NAVIGATION_ACTIONS[penultimateAction] || penultimateAction === 'newThought'))
-    )
+  const undoTwice = NAVIGATION_ACTIONS[lastAction]
+    ? penultimateUndoPatch && (penultimateAction ? UNDOABLE_ACTIONS[penultimateAction] : false)
+    : penultimateUndoPatch && penultimateAction === 'newThought'
```
Comment (raineorshine) [inline src/redux-enhancers/undoRedoEnhancer.ts:180]: There are some simplifications we can make to the logic here.

`a ? b : false` is equivalent to `a && b`:

```ts
const undoTwice = NAVIGATION_ACTIONS[lastAction]
    ? penultimateUndoPatch && (penultimateAction && UNDOABLE_ACTIONS[penultimateAction])
    : penultimateUndoPatch && penultimateAction === 'newThought'
```

We can simplify `penultimateAction && UNDOABLE_ACTIONS[penultimateAction]` to `UNDOABLE_ACTIONS[penultimateAction]` since the penultimate action must exist if it is in `UNDOABLE_ACTIONS`:

```ts
const undoTwice = NAVIGATION_ACTIONS[lastAction]
    ? penultimateUndoPatch && UNDOABLE_ACTIONS[penultimateAction]
    : penultimateUndoPatch && penultimateAction === 'newThought'
```

Finally, we can remove `penultimateUndoPatch` from the condition since it must be true whenever there is a `penultimateAction`:

```ts
  const undoTwice = NAVIGATION_ACTIONS[lastAction]
    ? UNDOABLE_ACTIONS[penultimateAction]
    : penultimateAction === 'newThought'
```

File: src/shortcuts/__tests__/undo.ts [hunk 2]
```diff
@@ -386,3 +386,50 @@ it('undo redo importText action', () => {
 
   expect(exportedAfterRedo).toEqual(expectedOutputAfterRedo)
 })
+
+it('cursor should restore to same thought if the thought has been edited after undo', () => {
+  const store = createTestStore()
+
+  store.dispatch([
+    newThought({ value: 'a' }),
+    newThought({ value: 'b' }),
```
Comment (raineorshine) [inline src/shortcuts/__tests__/undo.ts:395]: It would be better to emulate the user's action exactly by creating an empty thought, editing it to `a`, moving the cursor, creating another empty thought, and editing it to `b`. 

I abbreviate the steps to reproduce for readability, so apologies for the confusion.

File: src/shortcuts/__tests__/undo.ts [hunk 3]
```diff
@@ -386,3 +386,50 @@ it('undo redo importText action', () => {
...
+  ])
+
+  const expectedCursor = [{ value: 'a', rank: 0 }]
+
+  const cursorThoughts = childIdsToThoughts(store.getState(), store.getState().cursor!)
+
+  expect(cursorThoughts).toMatchObject(expectedCursor)
+})
+
+it('cursor should restore correctly after undo archive', async () => {
```
Comment (raineorshine) [inline src/shortcuts/__tests__/undo.ts:408]: Looks good!

**Review by raineorshine — CHANGES_REQUESTED** [review]

**Review by raineorshine — APPROVED** [review]
