### PR TITLE
Only make font weight 600 and up bold

### LINKED ISSUE #1566: Only make font weight 600 and up bold
## Steps to Reproduce

```
<ul>
  <li><i><b>The New Criterion</b></i><span style="font-weight: 400;"> is a </span>New York<span style="font-weight: 400;">–based monthly </span>literary magazine<span style="font-weight: 400;"> and journal of artistic and </span>cultural criticism<span style="font-weight: 400;">, 
edited by </span>Roger Kimball<span style="font-weight: 400;"> (editor and publisher) and </span>James Panero<span style="font-weight: 400;"> (executive editor). 
It has sections for criticism of poetry, theater, art, music, the media, and books. It was founded in 1982 by </span>Hilton Kramer<span style="font-weight: 400;">, former art critic for </span><i>The New York Times</i><span style="font-weight: 400;">, and Samuel Lipman, a pianist and music critic.</span>  </li>
</ul>
```

## Current Behavior

`font-weight: 400` is preserved on import. 

## Expected Behavior

`font-weight: 400` and below should be stripped on import. 

`font-weight: 500` and above should be converted to `<b>` or `font-weight: 700`.

### PR DESCRIPTION
**Pull request by karunkop**
Fixes #1566 

## Solution
- Check for correct condition before stripping tags in `stripStyleAttribute.ts`

### CODE REVIEW

**Comment by raineorshine** [comment]
Please add unit tests at your convenience. Include cases for font weight 200–800.

File: src/util/stripStyleAttribute.ts [hunk 1]
```diff
@@ -79,7 +79,9 @@ const stripStyleAttribute = (style: string) => {
       .filter(property => property.enabled !== false)
       .find(allowedStyleProperty => property.name.startsWith(allowedStyleProperty.property))
     if (styleProperty && (!styleProperty.test || styleProperty.test(property, styles))) {
-      return acc + `${property.name}: ${property.value};`
+      return property.name === 'font-weight' && +property.value >= 500
+        ? acc + `${property.name}: 700;`
+        : acc + `${property.name}: ${property.value};`
```
Comment (raineorshine) [inline src/util/stripStyleAttribute.ts:84]: Use ternaries at the narrowest possible level to reduce redundancies. Notice here that you repeat `acc + ${property.name}` in both cases. Instead, place the ternary inside the string template.

**Review by raineorshine — CHANGES_REQUESTED** [review]
The tests looks great! Just one small change in regard to eliminating redundancies.

File: src/util/stripStyleAttribute.ts [hunk 2]
```diff
@@ -79,9 +79,9 @@ const stripStyleAttribute = (style: string) => {
       .filter(property => property.enabled !== false)
       .find(allowedStyleProperty => property.name.startsWith(allowedStyleProperty.property))
     if (styleProperty && (!styleProperty.test || styleProperty.test(property, styles))) {
-      return property.name === 'font-weight' && +property.value >= 500
-        ? acc + `${property.name}: 700;`
-        : acc + `${property.name}: ${property.value};`
+      return (
+        acc + `${property.name}: ${property.name === 'font-weight' && +property.value >= 500 ? 700 : property.value};`
```
Comment (raineorshine) [inline src/util/stripStyleAttribute.ts:83]: Great. For readability, you can factor out the ternary into a constant.

**Review by raineorshine — APPROVED** [review]
