### PR TITLE
Show NewThoughtInstruction if there are no visible thoughts & Test

### LINKED ISSUE #843: Hide NewThoughtInstructions only when there are visible thoughts
Hide the `NewThoughtInstructions` component only when there are visible thoughts in the ROOT. Currently the message is hidden when there are any thoughts, regardless of visibility. 

## Steps to Reproduce

1. Create thought `a`
2. Archive `a`

## Current Behavior

Screen is empty. 

## Expected Behavior

Should show “Hit Enter to add a new thought”. 

## Tests

Write a unit test for the `Content` component.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #843 

@raineorshine Please test the changes. Thanks.

### CODE REVIEW

File: src/components/Content.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ const mapStateToProps = (state: State) => {
   const tutorialStep = isLoading ? tutorialStepLocal : +(getSetting(state, 'Tutorial Step') ?? 1)
 
   // do no sort here as the new object reference would cause a re-render even when the children have not changed
-  const rootThoughts = getThoughts(state, [ROOT_TOKEN])
+  const rootThoughts = getThoughts(state, [ROOT_TOKEN]).filter(({ value, rank }) => showHiddenThoughts || isChildVisible(state, [value], { value, rank }))
```
Comment (raineorshine) [inline src/components/Content.tsx:46]: I think you will have to `filter` within the `render` function. Otherwise `filter` creates a new object references and `mapStateToProps` will force a re-render even if the thoughts have not changed.

Comment (raineorshine) [reply src/components/Content.tsx:46]: It's also more efficient to check `showHiddenThought` outside the `filter` predicate since it is the same for all children.

File: src/components/__tests__/Content.js [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+beforeEach(async () => {
+  wrapper = await createTestApp()
+})
+
+afterEach(async () => {
+  await cleanupTestApp()
+  wrapper = null
+})
+
+it('show NewThoughtInstructions when there are no visible thoughts in the root context', async () => {
```
Comment (raineorshine) [inline src/components/__tests__/Content.js:18]: Test looks good!

**Comment by raineorshine** [comment]
If you have a trivial change like a typo and it has not been merged into `dev` yet, I recommend using `git commit --amend`.

File: src/components/Content.tsx (hunk 1 above)
Comment (shresthabijay) [reply src/components/Content.tsx]: Agreed!

File: src/components/Content.tsx [hunk 3]
```diff
@@ -43,15 +42,15 @@ const mapStateToProps = (state: State) => {
...
+  const rootThoughtsLength = (showHiddenThoughts ? getThoughts(state, [ROOT_TOKEN]) : getThoughts(state, [ROOT_TOKEN]).filter(({ value, rank }) => isChildVisible(state, [value], { value, rank }))).length
 
   return {
     focus,
     search,
     showModal,
     isTutorial,
     tutorialStep,
-    rootThoughts,
+    rootThoughtsLength,
```
Comment (raineorshine) [inline src/components/Content.tsx:53]: Won't this prevent a re-render when a thought has been edited?

Comment (shresthabijay) [reply src/components/Content.tsx:53]: It will re-render if the edit causes change of total number of visible children of root context. I don't think we need to re-render `Content` if edit doesn't cause visible children to change.

**Comment by shresthabijay** [comment]
@raineorshine  `Thought` component test is failing in the check. But it is passing in my local setup. Can you please check if it failing for you ?

File: src/components/Content.tsx (hunk 3 above)
Comment (raineorshine) [reply src/components/Content.tsx:53]: If other children change, such as from another data source, then we will need to re-render.

**Comment by raineorshine** [comment]
> @raineorshine `Thought` component test is failing in the check. But it is passing in my local setup. Can you please check if it failing for you ?

I re-ran the job and it passes. Still a timing issue in the `Thought` test that I am not able to reproduce.

**Comment by shresthabijay** [comment]
> > @raineorshine `Thought` component test is failing in the check. But it is passing in my local setup. Can you please check if it failing for you ?
> 
> I re-ran the job and it passes. Still a timing issue in the `Thought` test that I am not able to reproduce.

I tried to reproduce in my local system. But I was not able to. It's quite strange.

File: src/components/Content.tsx (hunk 3 above)
Comment (raineorshine) [reply src/components/Content.tsx:53]: @shresthabijay

Comment (shresthabijay) [reply src/components/Content.tsx:53]: > If other children change, such as from another data source, then we will need to re-render.

I don't understand. Can you explain briefly ?

My understanding is any changes in the store that cause number of visible child to change should re-render `Content`. Changes in other context should simply be handled by `Subthoughts` component.

Comment (raineorshine) [reply src/components/Content.tsx:53]: Oh, I guess you're right. I forgot that Subthoughts would take care of it. Or maybe I was thinking of before Subthoughts' `mapStateToProps` was changed.

**Review by raineorshine — APPROVED** [review]
