### PR TITLE
Prevent moving some meta thoughts on subCategorizeAll

### LINKED ISSUE #1244: subcategorizeAll should not move some meta attributes
## Steps to Reproduce

```js
- a
  - =note
    - My Note
  - c
```

1. Set the cursor on `a/c`. 
2. Activate `subcategorizeAll`. 

## Current Behavior

`=note` is moved to the new empty thought. 

## Expected Behavior

The following meta attributes should not move with `subcategorizeAll`:

- =archive
- =bullet
- =focus
- =label
- =note
- =pin
- =publish

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1244

# Changes

- Filter out meta exceptions on `subCategorizeAll`.
- Update tests.

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine  Please review the changes. Thanks!

File: src/reducers/__tests__/subCategorizeAll.ts [hunk 1]
```diff
@@ -89,28 +90,42 @@ it('set cursor on new empty thought', () => {
 
 })
 
-it('move all visible and hidden thoughts into a new empty thought after subcategorizeAll', () => {
+it('move all non meta thoughts and only allowed meta thoughts into new empty thought after subCategorizeAll', () => {
+
+  const metaExceptions = SUBCATEGORIZE_ALL_META_EXCEPTIONS.reduce(
+    (acc, meta, index) => (acc + `    - ${meta}${index === (SUBCATEGORIZE_ALL_META_EXCEPTIONS.length - 1) ? '' : '\n'}`)
+  , '')
```
Comment (raineorshine) [inline src/reducers/__tests__/subCategorizeAll.ts:97]: I would hardcode the exceptions into the test. We want tests to be as concrete as possible. Principles of abstraction that we use in application architecture do not apply in the test environment. It forces each case to be considered individually, which is what we want to do if there are new meta attributes.

Of course, we do generalize tests at times but we have to be careful to avoid complexity and abstraction when possible.

File: src/reducers/subCategorizeAll.ts [hunk 2]
```diff
@@ -42,6 +42,9 @@ const subCategorizeAll = (state: State) => {
   const children = getChildrenRanked(state, pathToContext(simplifyPath(state, path)))
   const pathParent = cursor.length > 1 ? cursorParent : HOME_PATH
 
+  // filter out meta children that should not be moved
+  const filteredChildren = children.filter(child => !SUBCATEGORIZE_ALL_META_EXCEPTIONS.includes(child.value))
```
Comment (raineorshine) [inline src/reducers/subCategorizeAll.ts:46]: Once the exceptions are hardcoded in the tests, we can move them out of constants into this module.

File: src/reducers/__tests__/subCategorizeAll.ts [hunk 3]
```diff
@@ -89,28 +90,42 @@ it('set cursor on new empty thought', () => {
...
+  expect(exported).toBe(`- ${HOME_TOKEN}
+  - a
+    - ${''/* prevent trim_trailing_whitespace */}
+      - =style
+      - =view
+      - c
+      - d
+      - e
+${metaExceptions}`)
+})
```
Comment (raineorshine) [inline src/reducers/__tests__/subCategorizeAll.ts:131]: Do you have your editor set up to use `.editorconfig`? It should not be allowing you to save files without final newlines. Unless that's a Windows thing.

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/reducers/__tests__/subCategorizeAll.ts (hunk 3 above)
Comment (shresthabijay) [reply src/reducers/__tests__/subCategorizeAll.ts:131]: No, I am using Macbook. I think the `eslint-config-prettier` is turning off some important eslint rules from `eslint-config-raine` and possibly other plugins too. All formatting related rules should be handled by the `prettier` now.

File: src/reducers/subCategorizeAll.ts (hunk 2 above)
Comment (shresthabijay) [reply src/reducers/subCategorizeAll.ts:46]: Sure will change this.

File: src/reducers/__tests__/subCategorizeAll.ts (hunk 1 above)
Comment (shresthabijay) [reply src/reducers/__tests__/subCategorizeAll.ts:97]: Understood.

File: src/reducers/__tests__/subCategorizeAll.ts (hunk 3 above)
Comment (raineorshine) [reply src/reducers/__tests__/subCategorizeAll.ts]: I don't think prettier has the equivalent of `insert_final_newline` from [EditorConfig](https://editorconfig.org/). You should install EditorConfig in your editor if you don't have it already.

This isn't related to eslint rules, but I am working with App Sapiens to make sure https://github.com/prettier/eslint-config-prettier is not a problem. It is disabling rules but only ones that Prettier can fix automatically.

Comment (raineorshine) [reply src/reducers/__tests__/subCategorizeAll.ts]: This issue seems to suggest that Prettier does this automatically: https://github.com/prettier/prettier/issues/2575

However it may depend on your editor settings.

File: src/reducers/subCategorizeAll.ts [hunk 4]
```diff
@@ -4,6 +4,16 @@ import { State } from '../util/initialState'
...
 
+const SUBCATEGORIZE_ALL_META_EXCEPTIONS = [
+  '=archive',
+  '=bullet',
+  '=focus',
+  '=label',
+  '=note',
+  '=pin',
+  '=publish',
+]
```
Comment (raineorshine) [inline src/reducers/subCategorizeAll.ts:15]: Can you use an object for this? The array is O(n) lookup while an object is O(1).

```ts
const SUBCATEGORIZE_ALL_META_EXCEPTIONS = {
  '=archive': true,
  '=bullet': true,
  ...
}
```

```ts
const filteredChildren =  childen.filter(child => child.value in SUBCATEGORIZE_ALL_META_EXCEPTIONS)
```

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/reducers/__tests__/subCategorizeAll.ts (hunk 3 above)
Comment (shresthabijay) [reply src/reducers/__tests__/subCategorizeAll.ts]: > I don't think prettier has the equivalent of `insert_final_newline` from [EditorConfig](https://editorconfig.org/). You ~should~ could install EditorConfig in your editor ~if you don't have it already.~ if it doesn't have a setting to automatically add a newline at the end of a file.

Sure.
