### PR TITLE
884

### LINKED ISSUE #884: Back/Forward after deleting results in invalid cursor
History back/forward should never result in an invalid cursor. History states with invalid `Paths` should be skipped. Thus if there are three invalid history states in a row (e.g. due to a thought being archived and `showHiddenThoughts` being `false`), then they should all be skipped and the next valid `Path` in the cursor history should be restored.

Start with a failing unit test.

## Steps to Reproduce

- a
- b
- c [cursor]

1. Create `a`, `b`, `c`, in order as shown above.
2. Select `a`.
2. Archive `a`.
3. Hit Back in the browser

## Current Behavior

Cursor disappears and url changes to `/a` even though `a` has been archived.

## Expected Behavior

Cursor should move to `c`.

### PR DESCRIPTION
**Pull request by anmolarora1**
fixes #884 

@raineorshine As discussed, this implementation is based on [our discussion](https://github.com/cybersemics/em/issues/884#issuecomment-734508411) over the issue. The back button works as expected, whereas the forward button doesn't. 
Please share your thoughts, and we'll proceed accordingly.

### CODE REVIEW

File: src/util/initEvents.ts [hunk 1]
```diff
@@ -16,16 +16,25 @@ declare global {
...
+  let lastState: number
+
   /** Popstate event listener; setCursor on browser history forward/backward. */
-  const onPopstate = () => {
+  const onPopstate = (e: PopStateEvent) => {
 
     const state = store.getState()
 
-    const { path, contextViews } = decodeThoughtsUrl(state, window.location.pathname)
+    const { path, contextViews } = decodeThoughtsUrl(state, window.location.pathname, { exists: true })
```
Comment (raineorshine) [inline src/util/initEvents.ts:27]: If you add `exists: true`, then `path` will be `null` in the case of a nonexistent pathname and you won't be able to differentiate it from the root context, as described here:

> It seems that `decodeThoughtsUrl` is a little inconsistent; when `exists: true` is given it returns `null` for a valid root context. This might be a bug.

https://github.com/cybersemics/em/issues/884#issuecomment-734508411

Not sure if that was intended, but I think with the current implementation of `decodeThoughtsUrl` you'll have to omit `exists` and use `pathExists` directly.

File: src/redux-middleware/updateUrlHistory.ts [hunk 2]
```diff
@@ -53,7 +52,8 @@ const updateUrlHistory = (state: State, path = RANKED_ROOT, { replace, contextVi
   // update browser history
   try {
     window.history[replace ? 'replaceState' : 'pushState'](
```
Comment (raineorshine) [inline src/redux-middleware/updateUrlHistory.ts:54]: There is something causing `[ROOT]` to get pushed onto the stack when skipping an invalid history state. This seems to happen on `dev` as well. I would suggest identifying the cause of that, as it might be interfering with the skipping back/forward functionality.

**Review by raineorshine — COMMENTED** [review]
Let me know how else I can help, or if you get stuck!

File: src/util/initEvents.ts (hunk 1 above)
Comment (anmolarora1) [reply src/util/initEvents.ts]: @raineorshine Removing `exists:true` solves the problem. You can test the functionality now.
As discussed, I'll look into the `decodeThoughtsUrl` bug and it's relation to the state in a different issue.

**Review by raineorshine — CHANGES_REQUESTED** [review]
Great, back and forward are working for the basic case now. One thing:

Duplicate states should also be skipped. i.e. if the user navigates `a`, `b`, `c`, `b`, and `c` gets deleted, then hitting back on `b` should go to `a`, not the other `b`.

**Comment by raineorshine** [comment]
Looks good, thanks!
