### PR TITLE
Remove debounce from removeSize

### LINKED ISSUE #3310: Subthought shifts up after expanding parent within 1 second of collapsing
Tested on iOS Safari. 

Related: #3097, #2783

## Steps to Reproduce

```
- a
- b
  - c
```

1. Set the cursor on `b`. 
2. Set the cursor to null. 
3. Within 1 second, set the cursor back to `b'. 
   - If you wait 1 second, the issue does not occur. 
   - This corresponds to the 1 second delay of the cached thought height in the size ref. 

## Current Behavior

`c` animated up as it fades in. 

https://github.com/user-attachments/assets/191ebb83-ab50-4cf3-b6d3-3f4b18650324

## Expected Behavior

`c` should only fade in, with no change in y position.

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #3310, hopefully supersedes #3640

I ripped out [setTimeout](https://github.com/ethan-james/em/blob/f954fce7c614f5cfa2bc5ed273930368ac6901b6/src/hooks/useSizeTracking.ts#L26) entirely, rather than calling `setTimeout` with a zero delay, which is another option in case this approach fails.

I tested it with the repro steps from #3310, and will continue to test it in other ways.

### CODE REVIEW

**Comment by ethan-james** [comment]
I do see that if there are 2 thoughts being shown/hidden, the upper one is still treated as a new cliff even thought it has a child that will also be shown.

https://github.com/user-attachments/assets/6807c52b-fb7b-4e5e-8834-d14e2c5a5d6f

It also exists in #3640 as well as `main`.

File: src/hooks/useSizeTracking.ts [hunk 1]
```diff
@@ -3,34 +3,23 @@ import { useSelector } from 'react-redux'
...
   // Track dynamic thought sizes from inner refs via VirtualThought. These are used to set the absolute y position which enables animation between any two states. isVisible is used to crop hidden thoughts.
   const [sizes, setSizes] = useState<Index<{ height: number; width?: number; isVisible: boolean }>>({})
   const fontSize = useSelector(state => state.fontSize)
   const unmounted = useRef(false)
 
-  // Track debounced height removals
-  // See: removeSize
-  const sizeRemovalTimeouts = useRef(new Map<string, number>())
-
   // Removing a size immediately on unmount can cause an infinite mount-unmount loop as the VirtualThought re-render triggers a new height calculation (iOS Safari only).
```
Comment (raineorshine) [inline src/hooks/useSizeTracking.ts]: You can remove the comment as well.

**Review by raineorshine — APPROVED** [review]

**Comment by raineorshine** [comment]
> I do see that if there are 2 thoughts being shown/hidden, the upper one is still treated as a new cliff even thought it has a child that will also be shown.

Thanks. If it's not currently being tracked, could you create a new issue for this?

**Review by raineorshine — APPROVED** [review]

**Review by BayuAri — COMMENTED** [review]
Confirmed that the bounce animation has been removed when displaying subthought from hidden state.


https://github.com/user-attachments/assets/1b237772-b8cc-48be-b4c1-e285cdd684e9
