### PR TITLE
Set cursor to first visible children or its parent after collapse

### LINKED ISSUE #1056: collapseContext moves cursor to hidden thought
# Case 1

## Steps to Reproduce

- a
  - b
    - =x

(`showHiddenThoughts` is `false`)
1. Move the cursor to `a/b`
2. Activate `collapseContext`

## Current Behavior

After the collapse, cursor is on `a/=x`

## Expected Behavior

After the collapse, if `showHiddenThoughts` is `false`, cursor should move to `a`. If `showHiddenThoughts` is `true`, cursor should move to `a/=x`. 

# Case 2

## Steps to Reproduce

- a
  - b
    - =x
    - c

1. Move the cursor to `a/b`
2. Activate `collapseContext`

## Current Behavior

After the collapse, cursor is on `a/=x`

## Expected Behavior

After the collapse, if `showHiddenThoughts` is `false`, cursor should move to `a/c`. If `showHiddenThoughts` is `true`, cursor should move to `a/=x`.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1056

### CODE REVIEW

**Comment by shresthabijay** [comment]
@raineorshine Please review the changes. Thanks!

File: src/reducers/__tests__/collapseContext.ts [hunk 1]
```diff
@@ -132,3 +132,36 @@ it('merge duplicate children', () => {
...
 })
+
+it('after collapse context set cursor to the first visible children.', () => {
+
+  const steps = [
+    newThought('a'),
+    newSubthought('b'),
+    newSubthought('=x'),
+    newThought('c'),
+    cursorBack,
```
Comment (raineorshine) [inline src/reducers/__tests__/collapseContext.ts:143]: Tip: I've found that a single `importText` makes for cleaner tests than several `newThought` or `newSubthought` calls. This is acceptable though.

**Review by raineorshine — APPROVED** [review]
