### PR TITLE
newThought: skip asyncFocus if selection.isThought

### LINKED ISSUE #2748: [Mobile] Scroll jumps on new thought after empty thought
Tested on iOS PWA. 

This only occurs when activating New Thought on an empty thought. Step 3, below, is just there to demonstrate that the problem does not occur when activating New Thought on a non-empty thought.  

Also note that this does not occur when scrollY is 0. 

## Steps to Reproduce

``` 
- a
  - b
``` 

1. Scroll down slightly so scrollY is not at 0. 
2. Set the cursor on `b`. 
3. New Thought *(notice how it does not autoscroll)*
4. Delete the new thought and edit `b` to the empty thought. 
5. New Thought. 

## Current Behavior

The window autoscrolls to the top. 

https://github.com/user-attachments/assets/1d4b0a0b-01ea-441e-be76-79331c0e7eff

## Expected Behavior

No autoscroll.

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #2748, #3075 and #3076

[asyncFocus](https://github.com/ethan-james/em/blob/7a51ebcb9c7263a0f306016f56d08fedf56c6c0a/src/actions/newThought.ts#L245)  was being called in the `newThought` action, which would usually trigger [dispatch(keyboardOpenActionCreator({ value: false }))](https://github.com/ethan-james/em/blob/7a51ebcb9c7263a0f306016f56d08fedf56c6c0a/src/components/Editable/useEditMode.ts#L123) in `useEditMode`. `newThought` would immediately dispatch a `setCursor` action that would generally cause the keyboard to stay open, but not always. Hypothetically, it would have more trouble when exceeding a frame's render budget, which would potentially explain why it's more common with longer lists.

`asyncFocus` is always called, but it doesn't trigger `keyboardOpen` if the following conditions are both true:
1. The thought has text in it
2. This is the first invocation of `newThought` after the app is reloaded
 
This doesn't exactly explain why the keyboard *only* ever closes when creating a new thought from an empty thought. It is possible to get `keyboardOpen: false` to fire by doing the following, starting from #3075:

1. Double-tap `Alabama` to edit
2. Hit enter
3. No `dispatch(keyboardOpenActionCreator({ value: false }))`
4. Hit backspace
5. Hit enter
6. Yes `dispatch(keyboardOpenActionCreator({ value: false }))`

...and yet I have never seen the keyboard close when starting from a thought with text in it. In #3075 you say `(sometimes it takes multiple times)` so maybe you have seen it when creating the first new thought. Although, presumably, not the *first* new thought because `keyboardOpen: false` would not fire if you started from `Alabama` and created a single new thought.

There is also another issue when deleting all of the empty thoughts created during testing, especially now that I've fixed the closing keyboard so it's possible to generate an enormous number of empty thoughts quickly. Start with the repro steps for #3076, then rapidly hit backspace to clear out all of the test thoughts. You should see the keyboard close because it's scrolling too quickly upward.

https://github.com/user-attachments/assets/fa5b46c6-7cf1-4028-bf30-196d1eaa4be0

~This also appears to be related to `asyncFocus`, [but a different use of asyncFocus](https://github.com/ethan-james/em/blob/f9a3d765950528e326c40a8ffe3ad762ace6a24c/src/components/Editable/useEditMode.ts#L89), and one which is already checking for `selection.isThought` so I will need to dig a little deeper and try to fix that as well.~

This appears to be related to delaying [setSelectionToCursorOffset](https://github.com/ethan-james/em/blob/f9a3d765950528e326c40a8ffe3ad762ace6a24c/src/components/Editable/useEditMode.ts#L92), which intermittently allows the keyboard to close before calling `setCursor`. Replacing `setTimeout` with `requestAnimationFrame` presumably shortens that delay and fixes the problem for reasons that I do not sufficiently understand and for now will refer to as "magic".

### CODE REVIEW

**Comment by ethan-james** [comment]
I tested this to make sure #999 is still fixed, and that it doesn't re-introduce an infinite loop. Looks OK to me.

File: src/actions/newThought.ts [hunk 1]
```diff
@@ -241,7 +242,9 @@ export const newThoughtActionCreator =
     // cancel if tutorial has just started
     if (tutorial && tutorialStep === TUTORIAL_STEP_START) return
 
-    if (!preventSetCursor && isTouch) {
+    // asyncFocus can cause disruptive autoscroll behavior, so it's important to avoid it when the selection is already on a thought.
```
Comment (raineorshine) [inline src/actions/newThought.ts:245]: Why does `asyncFocus` disrupt autoscroll behavior? Some more specificity here would help.

I also wonder if it would help if the `hiddenInput` was positioned in the center of the viewport. It would be nice to have a more resilient `asyncFocus` that worked regardless of the selection state before it is called, but maybe that's too ambitious.

File: src/components/Editable/useEditMode.ts [hunk 2]
```diff
@@ -83,12 +83,15 @@ const useEditMode = ({
 
         setTimeout fixes it, however it introduces an infinite loop when a nested empty thought is created.
         Not calling asyncFocus when the selection is already on a thought prevents the infinite loop.
+        Also, setTimeout creates a large enough delay that the keyboard will intermittently close on iOS Safari.
+        Replacing setTimeout with requestAnimationFrame closes that gap sufficiently and keeps the keyboard open
+        while rapidly deleting thoughts. (#3129)
```
Comment (raineorshine) [inline src/components/Editable/useEditMode.ts]: `setTimeout(..., 0)` is faster than `requestAnimationFrame`, so this explanation doesn't makes sense. e.g. 60 fps = 16ms per animation frame.

Do you have another explanation? I'd like to update this comment.

File: src/components/Editable/useEditMode.ts [hunk 3]
```diff
@@ -83,12 +83,15 @@ const useEditMode = ({
...
       */
         if (isTouch && isSafari()) {
           if (!selection.isThought()) {
             asyncFocus()
           }
-          setTimeout(setSelectionToCursorOffset)
+          requestAnimationFrame(setSelectionToCursorOffset)
```
Comment (raineorshine) [inline src/components/Editable/useEditMode.ts:94]: ~~I've tried `requestAnimationFrame` and it led to problems, but I can't recall what they were. I will test it both on a new thoughtspace and on my personal thoughtspace in case the added load makes a difference.~~

I don't see any issues, so we can go ahead and merge and keep an eye out for regressions in case we missed something.

**Review by raineorshine — COMMENTED** [review]
I haven't tested yet, but I have a few comments/questions.

**Comment by raineorshine** [comment]
> 2\. This is the first invocation of `newThought` after the app is reloaded

Why does `asyncFocus` behave differently on the first invocation?

**Comment by ethan-james** [comment]
> I also wonder if it would help if the `hiddenInput` was positioned in the center of the viewport. It would be nice to have a more resilient `asyncFocus` that worked regardless of the selection state before it is called, but maybe that's too ambitious.

I thought of positioning it differently, and it's definitely worth looking into whether that's the reason why it scrolls to the top.

> **The keyboard only closes when creating a new thought from an empty thought because `window.getSelection().focusNode.nodeType` is `Node.ELEMENT_NODE` on empty thoughts and `Node.TEXT_NODE` on non-empty thoughts.** This causes [selection.isText()](https://github.com/cybersemics/em/blob/7a51ebcb9c7263a0f306016f56d08fedf56c6c0a/src/device/asyncFocus.ts#L36) in `asyncFocus` to return false on empty thoughts and thus fail to prevent the focus as happens when activating New Thought on a non-empty thought.

What I see is:

- `Node.TEXT_NODE` when opening editing mode on an existing thought
- `Node.ELEMENT_NODE` during creation of any new thought (starting from text or empty thought)

This may explain why it behaves differently on the first invocation, although I'm not quite there yet. I can dig into this a little more tomorrow and see if I can prove it.

File: src/components/Editable/useEditMode.ts (hunk 2 above)
Comment (ethan-james) [reply src/components/Editable/useEditMode.ts]: I see:

Screenshot 2025-07-20 130031

My hunch is that `requestAnimationFrame` requests the current animation frame first, which would maybe explain why double-`rAF` is a thing. I'll see if I can find any literature on the subject.

Comment (ethan-james) [reply src/components/Editable/useEditMode.ts]: And I actually have lines ordered like:

```
          setTimeout(() => console.info(`setTimeout ${Date.now()}`))
          requestAnimationFrame(() => console.info(`requestAnimationFrame ${Date.now()}`))
```

so I don't think they share the same queue.

Comment (ethan-james) [reply src/components/Editable/useEditMode.ts]: Actually, if I log the time when the calls are scheduled, I see:

Screenshot 2025-07-20 131040

which indicates that `requestAnimationFrame` is, in fact, [executed just before the browser's next repaint](https://www.geeksforgeeks.org/javascript/settimeout-vs-requestanimationframe/) and `setTimeout` runs after the repaint. I changed it to ``setTimeout(() => console.info(`setTimeout ${Date.now()}`), 0)`` to make sure that I wasn't triggering some sort of undefined behavior by leaving off the explicit `0`, but it looks the same. Then I removed `requestAnimationFrame` entirely just to make sure, and `setTimeout` still runs after a ~15ms delay.

Comment (ethan-james) [reply src/components/Editable/useEditMode.ts]: Then I checked Chrome to see if it behaves more in line with how we'd expect, but saw similar results:

Screenshot 2025-07-20 132315

Comment (ethan-james) [reply src/components/Editable/useEditMode.ts]: In vanilla JS, I see it working the way you predicted, where `setTimeout` runs pretty much immediately and `requestAnimationFrame` waits until just before the repaint:

Screenshot 2025-07-20 135606

CodeSandbox: https://codesandbox.io/p/sandbox/6q9nly
Preview: https://6q9nly.csb.app/

The conclusion that I would tentatively draw is that the increased processing required in **em** frequently pushes `setTimeout` into the next frame, while `requestAnimationFrame` is guaranteed (hopefully?) to run before the next frame begins.

Comment (raineorshine) [reply src/components/Editable/useEditMode.ts]: > I see:
> 
> Screenshot 2025-07-20 130031
> My hunch is that `requestAnimationFrame` requests the current animation frame first, which would maybe explain why double-`rAF` is a thing. I'll see if I can find any literature on the subject.

Very interesting! I've only ever seen `setTimeout(..., 0)` resolve first, but I do know that the exact ms can very a lot depending on the CPU load. I know that has been a big source of flakiness in the puppeteer tests in the CI.

File: src/components/Editable/useEditMode.ts [hunk 4]
```diff
@@ -83,12 +83,15 @@ const useEditMode = ({
 
         setTimeout fixes it, however it introduces an infinite loop when a nested empty thought is created.
         Not calling asyncFocus when the selection is already on a thought prevents the infinite loop.
+        Also, setTimeout is frequently pushed into the next frame and the keyboard will intermittently close on iOS Safari.
+        Replacing setTimeout with requestAnimationFrame guarantees (hopefully?) that it will be processed before the next repaint,
+        keeping the keyboard open while rapidly deleting thoughts. (#3129)
       */
         if (isTouch && isSafari()) {
           if (!selection.isThought()) {
```
Comment (raineorshine) [inline src/components/Editable/useEditMode.ts:91]: Also notable that `!selection.isThought()` was already used here instead of `!selection.isText()`.
