### PR TITLE
Hide start/end faux caret on tap

### LINKED ISSUE #3666: [iOS] Faux caret intermittently shows for previous cursor
Tested on iOS Safari

## Steps to Reproduce

```
- A
  - B
    - C
```

1. Set the cursor on `C`. 
2. Set the caret at the start of `C`. 
3. Draw →↓→ to create a new subthought

## Current Behavior

Rarely, the faux caret shows on line `C` rather than the new line.

https://github.com/user-attachments/assets/18b2da69-e404-4615-9593-5eec1ace3b06

The bug appears only once at the very end.

## Expected Behavior

The faux caret should always appear on the new subthought.

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #3666 

The original issue was fixed in #3746, but there were still some double-faux-caret issues. Since [fauxCaretType](https://github.com/ethan-james/em/blob/d1995e6d404412272fc381ff6bdd07ab992f8617/src/hooks/useFauxCaretCssVars.ts#L26) for start/end faux carets is controlled independently from [the positioned faux caret](https://github.com/ethan-james/em/blob/d1995e6d404412272fc381ff6bdd07ab992f8617/src/components/FauxCaret.tsx#L61), it's possible for both of them to be active at the same time.

The straightforward solution that I tried here is to add a `fauxCaretTapHandler` that will hide the start/end faux carets when a thought is tapped. The only time that I can foresee where a faux caret would change from start/end to positioned is after a tap. It would also be possible to try and create a centralized enum that permits only one discrete type of faux caret to exist at a time.

### CODE REVIEW

File: src/hooks/useFauxCaretCssVars.ts [hunk 1]
```diff
@@ -60,10 +61,13 @@ const useFauxCaretNodeProvider = ({
...
-    '--faux-caret-line-end-opacity': fauxCaretType === 'thoughtEnd' ? undefined : 0,
-    '--faux-caret-note-line-start-opacity': fauxCaretType === 'noteStart' ? undefined : 0,
-    '--faux-caret-note-line-end-opacity': fauxCaretType === 'noteEnd' ? undefined : 0,
+    fauxCaretNodeProviderStyles: {
+      '--faux-caret-line-start-opacity': fauxCaretType === 'thoughtStart' ? undefined : 0,
+      '--faux-caret-line-end-opacity': fauxCaretType === 'thoughtEnd' ? undefined : 0,
+      '--faux-caret-note-line-start-opacity': fauxCaretType === 'noteStart' ? undefined : 0,
+      '--faux-caret-note-line-end-opacity': fauxCaretType === 'noteEnd' ? undefined : 0,
+    },
+    fauxCaretTapHandler: isTouch && isSafari() ? () => setFauxCaretType('none') : undefined,
```
Comment (raineorshine) [inline src/hooks/useFauxCaretCssVars.ts]: "Handler" is a name that only makes sense in the context of the `TreeNode`, where it used as the `onClick` handler. `useFauxCaretCssVars` doesn't know about event handlers or click events. It just exposes a way to hide the faux caret. Therefore, I would call this `hide`.

Similarly, `fauxCaretNodeProviderStyles` seems to namespace the variable name in anticipation of the caller. From the perspective of `useFauxCaretCssVars`, it's obvious that these styles are related to the faux caret, so that doesn't need to be part of the name. We can just call it `styles`. The caller can always rename it at declaration time if needed.

Lastly, I'm noticing that the handler is identical to the `editingValueStore` effect above. We could remove the duplication and define a single handler for both.

File: src/components/TreeNode.tsx [hunk 2]
```diff
@@ -153,10 +153,10 @@ const TreeNode = ({
         isMounted={isMounted}
         style={{
           ...style,
-          ...fauxCaretNodeProvider,
+          ...fauxCaretNodeProviderStyles,
         }}
       >
-        <div ref={fadeThoughtRef}>
+        <div ref={fadeThoughtRef} onClick={fauxCaretTapHandler}>
```
Comment (raineorshine) [inline src/components/TreeNode.tsx]: As usual, we should add inline comments for any logic that is not obvious in order to help future developers (including our future selves ☺️).

Why do we need to hide the faux caret on click? What would happen otherwise? What issue/PR is relevant?
