### PR TITLE
[Android] Fixed Bullet Rendering New (Glyph classes)

### LINKED ISSUE #103: Android: Fix bullet positioning
Make sure bullets are being rendered correctly on Android. There are six types of bullets, each of which may require specific CSS:

1. Closed Circle - for thoughts with no children
1. Open Circle - for thoughts with no children with context view activated
1. Closed Arrow right - for thoughts with children
1. Closed Arrow down - for expanded thoughts with children
1. Open Arrow right - for thoughts with context view activated
1. Open Arrow down - for expanded thoughts with context view activated

All bullet styles defined in App.css. For example:

https://github.com/cybersemics/em/blob/5de3fe6182634a2d3c8eead69274ba7da13d50da/src/App.css#L685-L703

Acceptable solution should contain screenshots of all bullet types.

## Reference screenshots

Closed arrow right:
bullet - closed arrow right

Closed arrow down:
bullet - closed arrow down

Open arrow right:
bullet - open arrow right

Open arrow down:
bullet - open arrow down

### PR DESCRIPTION
**Pull request by molecula451**
So far our lovely app was not rendering as we expected the bullets and it's different element. As soon as our elements changes to a new classes we made this new reflects and now they are working smooth and expected on a portrait phone and. We also went ahead a added some rules for responsiveness in Tablet landscape. All this for Android **(armv7I)**.

We've went a head a fixed all these components/elements. We have so far...

- **Closed Circle - for thoughts with no children**

closedcircle1

-  **Closed Arrow right - for thoughts with children**

closed arrow right and closed circcle

- **Closed Arrow down - for expanded thoughts with children**

closedarrowdown

- **Open Circle - for thoughts with no children with context view activated**

open circle for toughts with not children context view activate

- **Open Arrow right - for thoughts with context view activated**

open circle and open arrow right

- **Open Arrow down - for expanded thoughts with context view activated**

open arrow down

> We have tested and we already know our changes are not breaking any other elements or introducing any regressions. By far the changes are only taking care on the Android platforms

This PR shall closes #103 

**Testing Platforms**

Amazon Fire 7 **(1024 x 600)** Tablet
Blu Advance L4 (Portrait) **(480 x 800)**

### CODE REVIEW

**Comment by molecula451** [comment]
I am eager to hear you dear @raineorshine

File: src/browser.js [hunk 1]
```diff
@@ -3,6 +3,7 @@
 import * as uuid from 'uuid/v4'
 
 export const isMobile = /Mobile/.test(navigator.userAgent)
+export const isAndroid = navigator.platform === 'Linux armv7l'
```
Comment (raineorshine) [inline src/browser.js]: Wouldn't it just be `Android`?

Or, if a particular browser needs to be excluded, some more specific Android user agent detection: 
https://stackoverflow.com/a/19915132/480608

**Comment by raineorshine** [comment]
Can you post screenshots with the bullet positioning fixed? It should exactly match the desktop positioning. Those screenshots appear to still have positioning issues.

File: src/browser.js (hunk 1 above)
Comment (molecula451) [reply src/browser.js]: > Thanks! Are you able to test in a couple different mobile browsers on Android? Do we need to apply these styles to all Android browsers or just some?

This is a great question. However. our <code>navigator.platform</code> it's expecting one of these values. **Please see.**


navigatorplatform

Raine. However. We may use this one <code>/Android/.test(navigator.userAgent)</code> like the one we have with the <code>isMobile</code> but we are not stating our whole code to be executed for the Android Platform itself, instead this one it is solely depending on the different web browser user-agent detections (Chrome, Firefox, Opera, any others).

We this actual code we are stating that we want our platform to detect Android as our main device and therefore render the elements/properties we want with the different widths for different devices as a long as we state that in our code. And for responsiveness we are using the @media CSS statement. However we may need to add more for more devices. But the bullets like so are rendering as expected



> Wouldn't it just be `Android`?
> 
> Or, if a particular browser needs to be excluded, some more specific Android user agent detection:
> https://stackoverflow.com/a/19915132/480608

<code>navigator.platform</code> it's expecting **Linux i686** or **Linux armv7l** for Android. Most New Android Devices are armv7l. Therefore <code>Android</code> won't work for us as a value.

Comment (molecula451) [reply src/browser.js]: Raine. I must also tell you that the Browser or Platform that are not state are instead using the <code>isMobile</code> properties. Which is the default design and I know it work wells on your testing platform. But what I believe it's you need to consider revamping this state to any other like iOS instead I mean like specificying the actual device and therefore not be browser string dependant <code> navigator.userAgent </code>. But this is something I've been looking in the whole app. This is only for you to take in consideration and not an actual change I want to make neither from the bounty scope.

**Comment by molecula451** [comment]
> Can you post screenshots with the bullet positioning fixed? It should exactly match the desktop positioning. Those screenshots appear to still have positioning issues.

I suppose you are referring to these one we see here. 

We have:

**Open Circle and Open Arrow right**, and yes there is an alignment issue after these 2 friends are activate. I am taking care of right now.

open circle and open arrow right

File: src/browser.js (hunk 1 above)
Comment (raineorshine) [reply src/browser.js]: Thanks so much for the clarification. I was unaware of `navigator.platform` so that makes total sense now.

Yes, I agree that the platform/user agent detection needs a lot of work to become truly cross-platform. That will be another bounty :).

**Comment by raineorshine** [comment]
Thanks! You can use desktop Chrome as a reference point, or compare with these screenshots:

Closed arrow right:
bullet - closed arrow right

Closed arrow down:
bullet - closed arrow down

Open arrow right:
bullet - open arrow right

Open arrow down:
bullet - open arrow down

**Comment by raineorshine** [comment]
As of this morning I am on a meditation retreat for the next week and won’t have access to my computer or crypto wallet to pay out the bounty. I will review your submission as soon as I return on December 10th! Thanks!

**Comment by raineorshine** [comment]
Hi! Any update?

**Comment by molecula451** [comment]
Hi @raineorshine nice to have you again. Yes. This is pretty much work done. I am uploading the lastest capture so you see how we got it rendering. We have tested these properties also in (Silk) a built-in Browser for Amazon Fire. This confirms us that the properties are expecting to meet an Android device so it got it rendering.

**Comment by molecula451** [comment]
We have so far:

- [x] Closed circle
- [x] Closed Arrow Right and Down
- [x] Open Circle (**Context View Activated**) 
- [x] Open Arrow Right and Down **(Context View Activated**)

**Closed circle is smoother than ever.** Look how many toughts we can have in a row and they are rendering as expected

closedcircle

**Closed Arrow Right and Down**

closedarrowrightanddown

**Open Circle**

opencirclecontext

**Open Arrow Right and Down**

openarrowrightanddown

**Comment by molecula451** [comment]
@raineorshine at last. I fixed the spacing issue that you saw in the first screenshot of the PR. It's now as expected.

**Comment by raineorshine** [comment]
Hey! I need static screenshots at 100% zoom for final review. The video compression results in too many visual artifacts and doesn't allow me to make a precise comparison.

**Comment by molecula451** [comment]
> Hey! I need static screenshots at 100% zoom for final review. The video compression results in too many visual artifacts and doesn't allow me to make a precise comparison. See my last screenshots as good examples.

Sure thing. The gif are for you to see how they are rendering while the app it's actually working

**Comment by molecula451** [comment]
**Closed circle:**

closedcircle

**Open Circle:**

opencircle

**Closed Arrow Right:**

closedarrowright


**Closed Arrow Down:**

closedarrowdown

**Open Arrow Down:**

openarrowdown

**Open Arrow Right:**

openarrowright

**Comment by raineorshine** [comment]
Maybe it would be helpful if I provide a screenshot from desktop that isn't zoomed in so much:

Screen Shot 2019-12-09 at 4 44 12 PM

Notice the size of the bullets, as well as the vertical alignment.

By comparison:

> **Closed circle:**
> 
> closedcircle

I see two issues above:

1. The bullet is too small.
1. The bullet is not vertically centered with the text.

> **Closed Arrow Right:**
> 
> closedarrowright

The vertical alignment is much better above, although the bullet size is still off.

**Comment by molecula451** [comment]
> Fix bullet size and vertical alignment

I got you. This will only take me a few minutes. Please watch it

**Comment by molecula451** [comment]
> Fix bullet size and vertical alignment

fixedalignment

All bullets are now bigger. Vertical aligment was fixed. Take another look @raineorshine

**Comment by raineorshine** [comment]
Please re-examine my screenshots to reference bullet size. The bullet size should be much larger in relation to the text size than what you have.

The alignment looks very close on the closed circle, just move the bullet 1 or 2 pixels up. The alignment on the arrow appears to be significantly off still.

Try using the same text that you see in my screenshots so you can more easily compare.

Thanks!

**Comment by molecula451** [comment]
@raineorshine Have a look once.

I have increased the <code>font-size</code> property that is only for the closed circle and I have added the font-size property for the arrow so we can measure it independant from the other <code> font-size</code>

bullett

**Comment by molecula451** [comment]
@raineorshine What I believe is this. Please remember we are working with different devices and are different widths we are facing. As much as I am following your snaps wich all are very clear for me.

You may see that the bullet figure is slightly different from what we are seeing in Android

bullet

And the bullet from your iPhone

70482608-2e7a9b80-1aa3-11ea-84d8-0cad6a29dbfa

They are all tiny bit different but they still rendering as expected

Because you may see the actual proto live how it looks like here in Android:

Screenshot_20191210-133036

**Comment by raineorshine** [comment]
Good points. Thanks for the additional explanation and screenshots.

Since the original issue is only for alignment, not bullet size, it is only fair that I create a separate bounty for bullet size.

Thank you for your persistence!

**Comment by molecula451** [comment]
> Good points. Thanks for the additional explanation and screenshots.
> 
> Since the original issue is only for alignment, not bullet size, it is only fair that I create a separate bounty for bullet size.
> 
> Thank you for your persistence!

That's a good one @raineorshine it's nice to work with you. If am I allow it. I would ahead and open an issue so we discuss further details I will label it as [Enhacement] and you bounty ahead!

**Comment by raineorshine** [comment]
#211
