### PR TITLE
Fix getPrevRank

### LINKED ISSUE #970: Unhandled Rejection when activating new note after deleting subthought
## Steps to Reproduce

1. Create thought `a`
2. Create subthought `b`
3. Archive `b`
3. Activate new note

## Current Behavior

`Unhandled Rejection (TypeError): Cannot read property 'rank' of undefined`

> src/selectors/getPrevRank.ts:25

## Expected Behavior

New note is created without error.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #970

# Cause of Issue

The logic of `getPrevRank` didn't handled case where all the children in the context are hidden.

# Changes

- Add specific logic to handle above mentioned case in `getPrevRank`.
- Add appropriate selector test for `getPrevRank`.

### CODE REVIEW

File: src/selectors/__tests__/getPrevRank.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+  const steps = [
+    newThought('a'),
+    newSubthought('=archive'),
+    cursorBack
+  ]
+
+  const stateNew = reducerFlow(steps)(initialState())
+
+  const children = getAllChildren(stateNew, ['a'])
```
Comment (raineorshine) [inline src/selectors/__tests__/getPrevRank.ts:16]: Use `getAllChildrenSorted`, since we want the first child to have the lowest rank.

File: src/selectors/getPrevRank.ts [hunk 2]
```diff
@@ -16,8 +16,11 @@ const getPrevRank = (state: State, context: Context, { aboveMeta }: { aboveMeta?
     ? 0
     : children.findIndex(child => !isFunction(child.value))
 
+  // there could be no visible thoughts in the context
+  const noVisibleChildren = i === -1
+
   // between last metaprogramming attribute and first visible child
-  if (i === 0) return children[0].rank - 1
+  if (i === 0 || noVisibleChildren) return children[0].rank - 1
```
Comment (raineorshine) [inline src/selectors/getPrevRank.ts:23]: This is the correct behavior when `aboveMeta` is true. However if `aboveMeta` is false, the new rank should not be above hidden thought. I will add tests to clarify!

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/selectors/getPrevRank.ts (hunk 2 above)
Comment (shresthabijay) [reply src/selectors/getPrevRank.ts]: Got it!

File: src/selectors/__tests__/getPrevRank.ts [hunk 3]
```diff
@@ -1,20 +1,70 @@
...
-import { getAllChildren } from '../../selectors'
-import { newSubthought, newThought, cursorBack } from '../../reducers'
+import { initialState, isFunction, reducerFlow } from '../../util'
+import { RANKED_ROOT } from '../../constants'
+import { getAllChildrenSorted } from '../../selectors'
+import { importText, newSubthought, newThought } from '../../reducers'
 import getPrevRank from '../getPrevRank'
 
-it('getPrevRank when all the thoughts in the context are hidden', () => {
+it('get rank above all children', () => {
```
Comment (raineorshine) [inline src/selectors/__tests__/getPrevRank.ts]: @shresthabijay FYI You can exclude the module name from the individual tests since it is automatically included in the Jest output.

**Comment by raineorshine** [comment]
Looks good, thanks!
