### PR TITLE
Type meta attribute to move cursor

### LINKED ISSUE #1578: Type meta attribute to move cursor
When `showHiddenThoughts` is true, the meta attributes are visible and can be easily edited. When `showHiddenThoughts` is false, it's not so easy. The purpose of the feature is to provide an easy way to edit an existing meta attribute without having to toggle `showHiddenThoughts` on and off. It also avoids creating duplicate meta attributes.

For example, if there is a hidden attribute `=style` and I create a new sibling `=styl` [sic], then nothing happens. There is the hidden `=style` thought and the visible `=styl` thought (visible because the cursor is on it). As soon as the user types `e` on the end of `=styl`, it should recognize that the attribute already exists, delete `=styl`, and move the cursor to the existing `=style` thought. Once the cursor moves there, it will automatically become visible.

## Steps to Reproduce

``` 
- a
  - =style
    - color
      - lightblue
``` 

1. Set the cursor on `a` with hidden thoughts disabled. 
2. Create a new subthought 
3. Type `=style`

## Current Behavior

A new thought is created.

## Expected Behavior

If hidden thoughts are disabled, when the user types a meta attribute that already exists, delete the cursor thought and move the cursor to the end of the existing thought. 

In the above example, `color` and `lightblue` should appear under `=style`.

### PR DESCRIPTION
**Pull request by karunkop**
Fix #1578

## Problem
- Duplicate meta programming thought is created if the similar attribute exists within a context

## Solution

- Check for such condition within context where duplication is found for meta programming attributes
- Delete current cursor thought
- Set cursor to the already existing attribute within a context

### CODE REVIEW

File: src/reducers/editThought.ts [hunk 1]
```diff
@@ -32,6 +45,36 @@ const editThought = (
 
   const editedThought = getThoughtById(state, editedThoughtId)
 
+  const editedThoughtValue = editedThought.value
```
Comment (raineorshine) [inline src/reducers/editThought.ts:48]: No need for an extra variable here

File: src/reducers/editThought.ts [hunk 2]
```diff
@@ -32,6 +45,36 @@ const editThought = (
...
+
+  const parentThoughtIdsForCollidedThoughts = thoughtCollision?.contexts.map(
+    thoughtId => parentOfThought(state, thoughtId)?.id,
+  )
```
Comment (raineorshine) [inline src/reducers/editThought.ts:52]: You should not be using `thoughtCollision` at all. It checks if the new value exists anywhere else in the thoughtspace. This functionality is only concerned with sibling thoughts, and should not be iterating over every other thought in the thoughtspace with the same value.

You can use `Thought.childrenMap` for O(1) lookup of meta attributes, as they are keyed by value:

```ts
const styleThoughtId = thought.childrenMap['=style']
```

**Review by raineorshine — CHANGES_REQUESTED** [review]
Please add a unit test at your convenience. Thanks!

File: src/reducers/editThought.ts (hunk 2 above)
Comment (raineorshine) [reply src/reducers/editThought.ts:52]: Even better, use https://github.com/cybersemics/em/blob/dev/src/selectors/findDescendant.ts. That way the implementation details are hidden. It is optimized for attribute children.

File: src/reducers/editThought.ts [hunk 3]
```diff
@@ -32,6 +45,28 @@ const editThought = (
 
   const editedThought = getThoughtById(state, editedThoughtId)
 
+  const parentThoughtIdForEditedThought = parentOfThought(state, editedThoughtId)?.id
+
+  // only calculate decendant thought when current edited thought is a metaprogramming attribute
+
+  const thoughtIdForExistingMetaProgrammingThought =
```
Comment (raineorshine) [inline src/reducers/editThought.ts:52]: You should also check that the cursor is on the edited thought. `editThought` is called within various reducer flows, so you can't assume the edited thought is the cursor.

**Review by raineorshine — CHANGES_REQUESTED** [review]
I would suggest moving the new logic below the error checking.  Usually short circuiting logic goes first, and then the rest of the logic proceeds once the inputs have been validated.

File: src/reducers/editThought.ts [hunk 4]
```diff
@@ -49,6 +63,25 @@ const editThought = (
     console.warn(`Missing Lexeme: ${oldValue}`)
   }
 
+  // only calculate decendant thought when current edited thought is a metaprogramming attribute
+  const thoughtIdForExistingMetaProgrammingThought =
+    isFunction(newValue) &&
+    equalArrays(state.cursor || [], thoughtToPath(state, editedThought.id)) &&
```
Comment (raineorshine) [inline src/reducers/editThought.ts:69]: Rather than comparing the whole Path, just compare the head thought:

```ts
head(state.cursor) === editedThought.id
```

**Review by raineorshine — CHANGES_REQUESTED** [review]

**Review by raineorshine — APPROVED** [review]
