### PR TITLE
Fixed undo button being active although no undo action is available

### LINKED ISSUE #1495: Undo active even though no undo action available
## Steps to reproduce

```
- A
- 
```
Make thought A and hit enter. Undo 2 times.

## Current Behavior
Undo is active. Hitting undo causes error.

## Expected Behavior
Undo should not be active

### PR DESCRIPTION
**Pull request by nepali-prabhat**
fixes #1495 

## Changes
1. Updated the `isUndoEnabled` selector to return true only if there is some undo-able action in `inversePatches`.
2. Added optional chaining for functions in `undoRedoReducerEnhancer`.
3. Segregated `getLastActionType` function to utils.

### CODE REVIEW

File: src/selectors/isUndoEnabled.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { State } from '../@types'
+import { getLatestActionType } from '../util/getLastActionType'
 
 /** Determines if undo is enabled. */
-export const isUndoEnabled = (state: State) => !!state.inversePatches.length
+export const isUndoEnabled = (state: State) => getLatestActionType(state.inversePatches) !== undefined
```
Comment (raineorshine) [inline src/selectors/isUndoEnabled.ts:5]: You can omit `!== undefined` since it is the only falsey value possible.

File: src/shortcuts/redo.ts [hunk 2]
```diff
@@ -1,18 +1,9 @@
...
- * Recursively calculates last action type from patches history if it is one of the navigation actions and finally returns the action.
- */
-const getLatestActionType = (patches: Patch[], n = 1): string => {
-  const lastActionType = patches[patches.length - n]?.[0]?.actions[0]
-  if (NAVIGATION_ACTIONS[lastActionType]) return getLatestActionType(patches, n + 1)
-  return lastActionType
-}
+import { getLatestActionType } from '../util/getLastActionType'
 
 const redoShortcut: Shortcut = {
```
Comment (raineorshine) [inline src/shortcuts/redo.ts:8]: Could you change `isActive` to `canExecute` while we're at it? `isActive` only changes the highlighting, not the click state.

File: src/shortcuts/undo.ts [hunk 3]
```diff
@@ -1,18 +1,9 @@
...
- * Recursively calculates last action type from inversePatches history if it is one of the navigation actions and finally returns the action.
- */
-const getLatestActionType = (inversePatches: Patch[], n = 1): string => {
-  const lastActionType = inversePatches[inversePatches.length - n]?.[0]?.actions[0]
-  if (NAVIGATION_ACTIONS[lastActionType]) return getLatestActionType(inversePatches, n + 1)
-  return lastActionType
-}
+import { getLatestActionType } from '../util/getLastActionType'
 
 const undoShortcut: Shortcut = {
```
Comment (raineorshine) [inline src/shortcuts/undo.ts:8]: You can also change `isActive` to `canExecute` here as well.

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/shortcuts/redo.ts (hunk 2 above)
Comment (nepali-prabhat) [reply src/shortcuts/redo.ts:8]: Sure

**Review by raineorshine — APPROVED** [review]
Looks great!
