### PR TITLE
Don't dispatch setCursorOnThought if dragInProgress

### LINKED ISSUE #3051: Cursor moves to drag-and-dropped thought
## Steps to Reproduce

```
- a
```

1. Clear the cursor
2. Long press `a`
3. Move the pointer enough to trigger drag-and-drop
4. Release the pointer, with or without re-ordering `a`

## Current Behavior

Cursor moves to `a`.

## Expected Behavior

Cursor should remain cleared, or on another thought.

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #3051

I'm not quite sure why the transition from calling `onTap` on `mousedown` to calling it on `touchend` altered the flow, but now `setCursorOnThought` was being called at the end of a long press. Checking `dragInProgress` before the dispatch (which is delayed until after `useDragHold` has set `state.dragInProgress` to false) allows us to avoid calling `setCursorOnThought` as the result of a long press.

### CODE REVIEW

File: src/components/Editable.tsx [hunk 1]
```diff
@@ -571,6 +571,8 @@ const Editable = ({
 
       dispatch((dispatch, getState) => {
         const state = getState()
+        if (state.dragInProgress) return
```
Comment (raineorshine) [inline src/components/Editable.tsx:574]: This is a bit simpler, and avoids re-rendering every Editable when a drag starts or ends.

`useSelector` is preferred for reactive values. If the value is only used in an event handler, then it often doesn't need to be reactive.

**Review by raineorshine — APPROVED** [review]
Thank you!

File: src/components/Editable.tsx (hunk 1 above)
Comment (ethan-james) [reply src/components/Editable.tsx:574]: I commented on the code itself, but `dragInProgress` will be false inside the `dispatch`, because it waits a tick and happens after the `useDragHold` event handlers have already run.

Comment (raineorshine) [reply src/components/Editable.tsx:574]: It seems to still fix the issue though! 🤔

Tested on mobile Safari.

Comment (ethan-james) [reply src/components/Editable.tsx:574]: Yep, looks fine to me too!
