### PR TITLE
Split dragSource into dragSourceBullet and dragSourceEditable

### LINKED ISSUE #3239: Disallow drag-and-drop on empty space to the right of thoughts
Replaces #3085

Currently, a drag-and-drop can be initiated anywhere on the block level thought container, which extends to the right edge of the screen regardless of how long the thought is. This provides a wider zone to initiate drag-and-drop, but it has two problems:

1. Creates false positives in the scroll zone when the user is trying to scroll instead of drag.
2. Does not correspond well to the "drag and drop" metaphor itself (how can you pick up a thought by clicking empty space?)

This issue proposes to solve both of these problems by restricting the drag source to the editable rather than the entire thought container. A similar change was made for tap-to-edit some time ago, and the results have been positive.

## Steps to Reproduce

```
- This is a longer thought that will keep going and going and going so that it extends onto multiple lines.
- Hello
- World
```

Initial drag-and-drop to the right of "Hello" or "World" (green dotted line).

Image

## Current Behavior

Drag-and-drop _can_ be initiated with an initial long press on the block level thought-container element that extends to the right edge of the screen.

## Expected Behavior

Drag-and-drop should _not_ be allowed to the right of the editables. It should only be allowed on the editable itself (red background, including the 3em padding on the right edge).

### PR DESCRIPTION
**Pull request by ethan-james**
Fixes #3239 

Splitting into two drag sources works pretty well. I also moved the `draggable` attribute down into `Bullet` and `StaticThought` separately, and only apply the `dragSource` to `StaticThought` on mobile.

We are also back to the situation described in https://github.com/cybersemics/em/issues/3085#issuecomment-3310017154 where long press is still triggered by the thought container. Do you want me to try to move that into `Bullet` and `StaticThought` as well?

### CODE REVIEW

**Review by JoeDuong-dev — APPROVED** [review]
The fix for https://github.com/cybersemics/em/issues/3239 has been tested and verified. The highlighted green area in the example scenario no longer triggers a drag-and-drop action when the user taps and holds. This behavior was tested with various text lengths and layouts to ensure the functionality works correctly across different scenarios.

File: src/components/BulletPositioner.tsx [hunk 1]
```diff
@@ -294,6 +298,7 @@ const BulletPositioner = forwardRef<SVGSVGElement, PropsWithChildren<BulletPosit
         data-testid={cursorOverlay ? undefined : 'bullet-' + hashPath(path)}
         aria-label={cursorOverlay ? undefined : 'bullet'}
         data-highlighted={cursorOverlay ? undefined : isHighlighted}
+        ref={dragSource ? dndRef(ref => dragSource(ref)) : undefined}
```
Comment (raineorshine) [inline src/components/BulletPositioner.tsx:304]:
```suggestion
        ref={dragSource ? dndRef(dragSource) : undefined}
```

File: src/components/Thought.tsx [hunk 2]
```diff
@@ -537,14 +546,10 @@ const ThoughtContainer = ({
...
       {...dragHoldResult.props}
-      ref={dndRef(node => dragSource(dropTarget(node)))}
+      ref={dndRef(node => dragPreview(dropTarget(node)))}
       aria-label='child'
       data-divider={isDivider(value)}
       data-editing={isEditing}
-      // HTML5Backend will override this to be "true" on platforms that use it.
-      // iOS Safari needs it to be true to disable native long press behavior. (#2953, #2931, #2964)
-      // Android works better if draggable is false.
-      draggable={isTouch && isSafari()}
```
Comment (raineorshine) [inline src/components/Thought.tsx:547]: Did something change on iOS Safari where it is no longer needed?

**Review by raineorshine — CHANGES_REQUESTED** [review]
Thank you! There are a few other things that need to be brought into alignment in the UX when long pressing the empty space for it to be a true dead zone:

- No bullet highlight
- No Alert
- No Command Center

Sorry for not mentioning these explicitly in the original issue!

**Comment by ethan-james** [comment]
> Thank you! There are a few other things that need to be brought into alignment in the UX when long pressing the empty space for it to be a true dead zone:
> 
> * No bullet highlight
> * No Alert
> * No Command Center
> 
> Sorry for not mentioning these explicitly in the original issue!

That's OK, I asked earlier if long press should be given the same treatment, and it sounds like the answer is yes.

File: src/components/Thought.tsx (hunk 2 above)
Comment (ethan-james) [reply src/components/Thought.tsx:547]: I moved it into `StaticThought` where the `dragSource` is now. I neglected to add `draggable` to `Bullet` as well, but I just tested it and it seems OK without on iOS Safari. Probably because the native editable long press behavior that we were over-riding doesn't exist on the bullet.

Comment (raineorshine) [reply src/components/Thought.tsx:547]: I see now! Thanks!

**Comment by ethan-james** [comment]
I moved `dragHoldResult.props`, which controls long press behavior, down into `StaticThought` and `BulletPositioner`. Since long press behavior isn't as sensitive as drag behavior, I wasn't sure whether it would be better to call `useDragHold` in each of those components rather than passing the props down into them. Let me know if you have a preference.
