### PR TITLE
Use pullLexemes to pull pending lexemes for each batch

### LINKED ISSUE #1074: New thoughts not merged into pending lexemes
## Steps to Reproduce

```
- a
- b
  - c
    - d
      - e
        - f
```

1. Set the cursor on `a`. 
1. Refresh the page.
2. Hit Enter to create a new thought and edit it to `f`.

## Current Behavior

`f` has no superscript.

~~If the page is refreshed, the superscript appears, indicating that the Lexeme was actually updated correctly in the db.~~ (No longer true as of the initial merge of the treecrdt.)

## Expected Behavior

`f` should have superscript 2.

## Testing

Unskip https://github.com/cybersemics/em/blob/5e38e2028a34c620d06bf52b530ff3cd12c7e069/src/redux-middleware/__tests__/pushQueue.ts#L16.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1074 

# Changes

- Add `pendingLexemes` to `PushBatch`. Calculating `pendingLexemes`  in `pushQueue` won't work as the application state is already updated in `updatedThoughts`. So it needs to be done in `updatedThoughts` and added to the batch.
- `pushQueue` now first checks for `pendingLexemes` in the batches and calls `pullLexemes`. `pullLexemes` gets the lexeme from local and remote source and reconciles them.
- `reconcile` is updated to call `updateThoughts` if only `thoughtIndexOnly` is available.

### CODE REVIEW

File: src/reducers/__tests__/deleteEmptyThought.ts [hunk 1]
```diff
@@ -248,28 +251,32 @@ describe('mount', () => {
...
 
-  it('after deleteEmptyThought, caret should move to end of previous thought', () => {
-    store.dispatch([
-      { type: 'newThought', value: 'apple' },
-      { type: 'newThought' },
-      { type: 'deleteEmptyThought' }
-    ])
-    jest.runOnlyPendingTimers()
+  it('after deleteEmptyThought, caret should move to end of previous thought', async () => {
+    await fakeTimer.runAsyncCode(() => {
```
Comment (raineorshine) [inline src/reducers/__tests__/deleteEmptyThought.ts:255]: Could you explain the reason for adding `runAsyncCode` here? I'd like to understand this more.

File: src/reducers/updateThoughts.ts [hunk 2]
```diff
@@ -62,6 +62,15 @@ const updateThoughts = (state: State, { thoughtIndexUpdates, contextIndexUpdates
 
   const recentlyEditedNew = recentlyEdited || state.recentlyEdited
 
+  //  lexemes from the updates that are not available in the state yet.
+  const pendingLexemes = Object.keys(thoughtIndexUpdates).reduce<Index<string>>((acc, thoughtId) => {
+    const lexemeInState = state.thoughts.thoughtIndex[thoughtId]
+    return {
+      ...acc,
+      ...lexemeInState ? {} : { [thoughtId]: thoughtId }
```
Comment (raineorshine) [inline src/reducers/updateThoughts.ts:70]: Why use `{ [thoughtId]: thoughtId }` instead of an array of `thoughtId`? Do you need O(1) lookup? 

If so, I'd suggest `{ [thoughtId]: true }` anyway which is a little cleaner and forces downstream code to use `Object.keys` instead of either `Object.keys` and `Object.values`, which could result in mixed use.

File: src/redux-middleware/pushQueue.ts [hunk 3]
```diff
@@ -139,13 +133,54 @@ const flushPushQueue = (): Thunk<Promise<void>> => async (dispatch, getState) =>
...
+      ...acc,
+      ...lexemeInUpdatedState ? { [thoughtId]: { ...lexemeInBatch, contexts: [...lexemeInBatch.contexts, ...updatedLexemeContexts()] } } : {}
+    }
+  }, {})
+
+  // Pull all the pending lexemes that are not available in state yet, reconcile and update the thoughtIndexUpdates. Prevents local and remote lexemes getting overriden by incomplete application state (due to lazy loading).
+  // Related issue: https://github.com/cybersemics/em/issues/1074
+  const lexemeSyncedPushQueue = await Promise.all(pushQueue.map(async batch => {
+    if (!batch.pendingLexemes || Object.keys(batch.pendingLexemes).length === 0) return batch
+    await dispatch(pullLexemes(Object.values(batch.pendingLexemes!)))
```
Comment (raineorshine) [inline src/redux-middleware/pushQueue.ts:169]: I think we need to collate `pendingLexemes` and then make a single `pullLexemes` call, as one `pullLexemes` for every batch is inefficient and defeats the purpose of the `pushQueue`, which is to throttle database access. The logic is already there with `mergeBatch`. You just need to add `pendingLexemes` to `mergeBatch` and then use that instead of pulling every batch separately.

If you need to have access to `lexemeSyncedPushQueue` before `mergeBatch` is called for some reason, then you may need to merge the `pendingLexemes` manually, but I still think we want to find a way to use a single `pullLexemes`.

Let me know if this doesn't make sense or if I'm missing something!

File: src/redux-middleware/pushQueue.ts [hunk 4]
```diff
@@ -139,13 +133,54 @@ const flushPushQueue = (): Thunk<Promise<void>> => async (dispatch, getState) =>
...
-  dispatch(flushMoves())
+  /**
+   * Returns updated thoughtIndexUpdates using the latest state after pulling pending lexemes.
+   */
+  const getSyncedThoughtsUpdate = (batch: PushBatch) => Object.keys(batch.thoughtIndexUpdates).reduce<Index<Lexeme | null>>((acc, thoughtId) => {
+
+    const updatedState = getState()
+
+    // Return early if this particular lexeme was not pending
+    const hadPendingLexeme = batch.pendingLexemes?.[thoughtId]
```
Comment (raineorshine) [inline src/redux-middleware/pushQueue.ts:144]: Idea: Is it possible to calculate `batch.pendingLexemes` here instead of in `updateThoughts`? It isn't possible with `pendingMoves` for example which needs information from `existingThoughtMoves`, but `pendingLexemes` is a simple comparison with the state. One less dependency and one batch variable.

File: src/redux-middleware/pushQueue.ts [hunk 5]
```diff
@@ -139,13 +133,54 @@ const flushPushQueue = (): Thunk<Promise<void>> => async (dispatch, getState) =>
 
   if (pushQueue.length === 0) return Promise.resolve()
 
-  dispatch(flushDeletes())
-  dispatch(flushEdits())
-  dispatch(flushMoves())
+  /**
+   * Returns updated thoughtIndexUpdates using the latest state after pulling pending lexemes.
+   */
+  const getSyncedThoughtsUpdate = (batch: PushBatch) => Object.keys(batch.thoughtIndexUpdates).reduce<Index<Lexeme | null>>((acc, thoughtId) => {
```
Comment (raineorshine) [inline src/redux-middleware/pushQueue.ts:139]: Instead of taking the whole `batch` you can just take `pendingLexemes` and `thoughtIndexUpdates`, which is a narrower dependency.

File: src/redux-middleware/pushQueue.ts [hunk 6]
```diff
@@ -139,13 +133,54 @@ const flushPushQueue = (): Thunk<Promise<void>> => async (dispatch, getState) =>
...
+
+    const updatedState = getState()
+
+    // Return early if this particular lexeme was not pending
+    const hadPendingLexeme = batch.pendingLexemes?.[thoughtId]
+    if (!hadPendingLexeme) return acc
+
+    // Note: Assuming thoughtIndexUpdates entry with null value won't occur, as they will have associated lexeme already pulled.
+    const lexemeInBatch = batch.thoughtIndexUpdates[thoughtId] as Lexeme
```
Comment (raineorshine) [inline src/redux-middleware/pushQueue.ts:148]: Use `batch.thoughtIndexUpdates[thoughtId]!`

File: src/redux-middleware/pushQueue.ts [hunk 7]
```diff
@@ -139,13 +133,54 @@ const flushPushQueue = (): Thunk<Promise<void>> => async (dispatch, getState) =>
...
+   */
+  const getSyncedThoughtsUpdate = (batch: PushBatch) => Object.keys(batch.thoughtIndexUpdates).reduce<Index<Lexeme | null>>((acc, thoughtId) => {
+
+    const updatedState = getState()
+
+    // Return early if this particular lexeme was not pending
+    const hadPendingLexeme = batch.pendingLexemes?.[thoughtId]
+    if (!hadPendingLexeme) return acc
+
+    // Note: Assuming thoughtIndexUpdates entry with null value won't occur, as they will have associated lexeme already pulled.
```
Comment (raineorshine) [inline src/redux-middleware/pushQueue.ts:147]: Could you clarify "they will have associated lexeme already pulled"? Are null updates somehow removed before this point?

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/reducers/updateThoughts.ts (hunk 2 above)
Comment (shresthabijay) [reply src/reducers/updateThoughts.ts:70]: > Why use `{ [thoughtId]: thoughtId }` instead of an array of `thoughtId`? Do you need O(1) lookup?

Yes. We need O(1) lookup here in `getSyncedThoughtsUpdate`. Else we will have to iterate the array every time to check if a particular lexeme was pending or not.

https://github.com/shresthabijay/em/blob/5ec0459fe264dd8ab5f8683fac5a2976cd12e2db/src/redux-middleware/pushQueue.ts#L144

File: src/redux-middleware/pushQueue.ts (hunk 4 above)
Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:144]: I don't think so. `updateThoughts` updates the `thoughts` itself and we need to compare `batch` `thoughtIndexUpdates` against the current `thoughts`, not the updated one. In `pushQueue` we will already have the updated state so comparison will show no differences.

File: src/redux-middleware/pushQueue.ts (hunk 5 above)
Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:139]: Sure.

File: src/redux-middleware/pushQueue.ts (hunk 7 above)
Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:147]: null updates are caused by thought deletion. For thought deletion, we already need to pull the associated lexemes and parent (from the pullQueue). So after null updates won't run into a state where the associated lexeme is not available. Please correct me if I am wrong to assume this.

File: src/redux-middleware/pushQueue.ts (hunk 6 above)
Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:148]: Sure

File: src/redux-middleware/pushQueue.ts (hunk 3 above)
Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:169]: Thanks. It makes sense.

File: src/redux-middleware/pushQueue.ts (hunk 7 above)
Comment (raineorshine) [reply src/redux-middleware/pushQueue.ts:147]: An edit consists of a null update + a new or modified update. There will be no conflicting Lexemes from a null update, but that doesn't mean there are no null updates. 

Or do you mean we know there will be no null updates because of the check on L168 of pushQueue?

Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:147]: `pendingLexemes` are the `thoughtIndexUpdates` that do not have an entry in the `thoughtIndex`. For all null `thoughtIndexUpdates`, there would always be an entry in the `thoughtIndex` as they are pulled by the `pullQueue` before the delete operation.

Comment (raineorshine) [reply src/redux-middleware/pushQueue.ts:147]: Is it the conditional above, `if (!hadPendingLexeme) return acc`, that ensures this? If not, I give up 😅

Comment (shresthabijay) [reply src/redux-middleware/pushQueue.ts:147]: > Is it the conditional above, `if (!hadPendingLexeme) return acc`, that ensures this? If not, I give up 😅

Yes. It checks if the update was pending or not.

**Comment by shresthabijay** [comment]
@raineorshine I have made the changes.
- Updated `createTestApp` to flush all the promises before the test starts. Asynchronous calls from the previous `createTestApp` were actually affecting the state of the new tests. It was causing the actual problem in tests.
- Merged `pendingLexemes` and called a single `pullLexeme` call.
- Add tests for this specific issue.

File: src/reducers/__tests__/deleteEmptyThought.ts [hunk 8]
```diff
@@ -248,29 +248,26 @@ describe('mount', () => {
...
-  it('after deleteEmptyThought, caret should move to end of previous thought', () => {
+  it('after deleteEmptyThought, caret should move to end of previous thought', async () => {
     store.dispatch([
       { type: 'newThought', value: 'apple' },
       { type: 'newThought' },
       { type: 'deleteEmptyThought' }
     ])
-    jest.runOnlyPendingTimers()
-    expect(window.getSelection()?.focusOffset).toBe('apple'.length)
   })
```
Comment (raineorshine) [inline src/reducers/__tests__/deleteEmptyThought.ts:257]: There is no longer an assertion in this test

**Review by raineorshine — CHANGES_REQUESTED** [review]
Great! I think it's really coming together now.

File: src/redux-middleware/__tests__/pushQueue.ts [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+const fakeTimer = testTimer()
+
+const db = dexie as DataProvider
+
+beforeEach(async () => {
+  fakeTimer.useFakeTimer()
+  initialize()
+  await fakeTimer.runAllAsync()
+  fakeTimer.useRealTimer()
+})
```
[the remark this answers is not in the document]
Comment (shresthabijay) [reply src/redux-middleware/__tests__/pushQueue.ts:26]: It doesn't need to test components. But it would be alright to use `createTestApp` instead of using `initialize` and  fake timers here. I will change it.

File: src/redux-middleware/__tests__/pushQueue.ts [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+
+afterEach(async () => {
+  fakeTimer.useFakeTimer()
+  store.dispatch(clear())
+  await fakeTimer.runAllAsync()
+  fakeTimer.useRealTimer()
+  await db.clearAll()
+})
+
+it('if pending lexemes are found in push batches then pull lexemes, reconcile and update the thoughtIndexUpdates before they are pushed', async () => {
```
[the remark this answers is not in the document]
Comment (shresthabijay) [reply src/redux-middleware/__tests__/pushQueue.ts:36]: Sure

File: src/redux-middleware/__tests__/pushQueue.ts [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+
+  initialize()
+  await fakeTimer.runAllAsync()
+
+  fakeTimer.useRealTimer()
+
+  // lexeme for 'f; should not be loaded into the state yet.
+  expect(getThoughtSelector(store.getState(), 'f')).toBeFalsy()
+
+  fakeTimer.useFakeTimer()
```
[the remark this answers is not in the document]
Comment (shresthabijay) [reply src/redux-middleware/__tests__/pushQueue.ts:76]: Ahh! I will remove it.

File: src/redux-middleware/__tests__/pushQueue.ts [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+    oldValue: 'h',
+    newValue: 'f',
+    context: ['g'],
+    path: [{ value: 'g', rank: 0 }, { value: 'h', rank: 0 }] as SimplePath,
+  }))
+  await fakeTimer.runAllAsync()
+
+  fakeTimer.useRealTimer()
+
+  // after existing thought change the pushQueue should pull the pending lexemes and update the thoughtIndexUpdates accordingly.
```
[the remark this answers is not in the document]
Comment (shresthabijay) [reply src/redux-middleware/__tests__/pushQueue.ts:88]: Sure.

File: src/redux-middleware/__tests__/pushQueue.ts [hunk 13]
```diff
@@ -0,0 +1,96 @@
...
+
+  // clear state
+  // call initialize again to reload from db (simulating page refresh)
+
+  fakeTimer.useFakeTimer()
+  store.dispatch(clear())
+  await fakeTimer.runAllAsync()
+
+  initialize()
+  await fakeTimer.runAllAsync()
```
[the remark this answers is not in the document]
Comment (shresthabijay) [reply src/redux-middleware/__tests__/pushQueue.ts:69]: Sure. We can use that test helper in other places like `pullQueue` tests too.

**Review by raineorshine — APPROVED** [review]
