### PR TITLE
Normalize thought for duplication check in editable

### LINKED ISSUE #1132: Disallow siblings with same lexeme
## Steps to Reproduce

1. Create thought `cat`
2. Create thought `cats`

## Current Behavior

- cat
- cats

## Expected Behavior

“Duplicate thoughts” alert should occur for siblings that would have the same `Lexeme` i.e. hash to the same value. They should be treated just like exact duplicates (e.g. “cat”) in style, behavior, alert, etc.

### PR DESCRIPTION
**Pull request by shresthabijay**
fixes #1132

### CODE REVIEW

File: src/components/Editable.tsx [hunk 1]
```diff
@@ -439,7 +440,7 @@ const Editable = ({ disabled, isEditing, simplePath, path, cursorOffset, showCon
     const oldValueClean = oldValue === EM_TOKEN ? 'em' : ellipsize(oldValue)
 
     const thoughtsInContext = getAllChildren(state, context)
-    const hasDuplicate = newValue !== '' && thoughtsInContext.some(thought => thought.value === newValue)
+    const hasDuplicate = newValue !== '' && thoughtsInContext.some(thought => normalizeThought(thought.value) === normalizeThought(newValue))
```
Comment (raineorshine) [inline src/components/Editable.tsx:443]: You’ll want to normalize `newValue` outside the loop for efficiency.

**Review by raineorshine — CHANGES_REQUESTED** [review]

File: src/components/Editable.tsx (hunk 1 above)
Comment (shresthabijay) [reply src/components/Editable.tsx]: Sure

**Review by raineorshine — APPROVED** [review]

**Comment by raineorshine** [comment]
Thanks!
