### PR TITLE
Fix: Child with same value as parent breaks cursor

### LINKED ISSUE #824: Child with same value as parent breaks cursor
## Steps to Reproduce

1. Create thought `a`
2. Create subthought `ab` (by typing `a` then `b`)

## Current Behavior

`cursor` becomes `[{ value: 'ab', rank: 0 }, { value: 'ab', rank: 0 }]`

## Expected Behavior

`cursor` should be `[{ value: 'a', rank: 0 }, { value: 'ab', rank: 0 }]`

## Notes

When the ranks differ, the problem does not occur:

- a
  - x
  - a

1. Create thought `a`
2. Create subthought of `a`: `x`
3. Create subthought of `a`: `a`
4. Edit `/a/a` to `/a/ab`

This will correctly result in `cursor: [{ value: 'a', rank: 0 }, { value: 'ab', rank: 1 }]`

### PR DESCRIPTION
**Pull request by pushkov-fedor**
Fixes #824

### CODE REVIEW

File: src/reducers/existingThoughtChange.ts [hunk 1]
```diff
@@ -56,18 +56,12 @@ const existingThoughtChange = (state: State, { oldValue, newValue, context, show
...
   const archived = exactThought ? exactThought.archived : null
-
-  const cursorNew = state.cursor && state.cursor.map(thought => thought.value === oldValue && thought.rank === (rankInContext || rank)
-    ? { value: newValue, rank: thought.rank }
-    : thought
-  )
-
-  const newPath = thoughtsRanked.slice(0, thoughtsRanked.length - 1).concat({ value: newValue, rank: thoughtsRanked.slice(thoughtsRanked.length - 1)[0].rank })
+  const cursorNew = state.cursor && [...state.cursor.slice(0, -1), { ...head(state.cursor), value: newValue }]
+  const newPath = thoughtsRanked.slice(0, thoughtsRanked.length - 1).concat({ value: newValue, rank: rankInContext || rank })
```
Comment (raineorshine) [inline src/reducers/existingThoughtChange.ts:64]: Please do not use array methods on `Path` types. They are meant to be ADT's with clear methods of interaction. The underlying array is an implementation detail that consumers should not be aware of.

Use `head` and `contextOf`.

**Comment by raineorshine** [comment]
Thanks!
